sudo: required
services:
  - docker

before_install:
  - docker build -t ajmeraabhishek/test-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  ajmeraabhishek/test-react npm run test -- --coverage

after_success:
 - docker build -t ajmeraabhishek/multi-client ./client
 - docker build -t ajmeraabhishek/multi-nginx ./nginx
 - docker build -t ajmeraabhishek/multi-server ./server
 - docker build -t ajmeraabhishek/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push ajmeraabhishek/multi-client
 - docker push ajmeraabhishek/multi-nginx
 - docker push ajmeraabhishek/multi-server
 - docker push ajmeraabhishek/multi-worker

