sudo: required
services:
  - docker

before_install:
  - docker build -t abhishekajmera/test-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  abhishekajmera/test-react npm run test -- --coverage

after_success:
 - docker build -t abhishekajmera/multi-client ./client
 - docker build -t abhishekajmera/multi-nginx ./nginx
 - docker build -t abhishekajmera/multi-server ./server
 - docker build -t abhishekajmera/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push abhishekajmera/multi-client
 - docker push abhishekajmera/multi-nginx
 - docker push abhishekajmera/multi-server
 - docker push abhishekajmera/multi-worker
